CREATE USER IF NOT EXISTS ADMIN SALT '31fb82132ce89dc4' HASH '6a692dbd91ba088180384e5dfcbbbf19c6e930bbf2af4bd0cf35a1e057d91845' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DEE8149F_D4B4_413D_9032_511DCDF6D45F START WITH 3 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 4;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_027150CA_4473_413D_834C_48D27A10D6E2 START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9F8EBA1E_9F52_4CEC_8BE5_6ACBB342DCEA START WITH 4 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC."flyway_schema_history"
(
    "installed_rank" INT                                 NOT NULL,
    "version"        VARCHAR(50),
    "description"    VARCHAR(200)                        NOT NULL,
    "type"           VARCHAR(20)                         NOT NULL,
    "script"         VARCHAR(1000)                       NOT NULL,
    "checksum"       INT,
    "installed_by"   VARCHAR(100)                        NOT NULL,
    "installed_on"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INT                                 NOT NULL,
    "success"        BOOLEAN                             NOT NULL
);
ALTER TABLE PUBLIC."flyway_schema_history"
    ADD CONSTRAINT PUBLIC."flyway_schema_history_pk" PRIMARY KEY ("installed_rank");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC."flyway_schema_history";
CREATE INDEX PUBLIC."flyway_schema_history_s_idx" ON PUBLIC."flyway_schema_history" ("success");
CREATE CACHED TABLE PUBLIC.MARK
(
    ID              BIGINT NOT NULL,
    ASSIGNMENT_DATE DATE,
    DESCRIPTION     VARCHAR(200),
    SUBJECT_ID      BIGINT,
    TEACHER_ID      BIGINT,
    PUPIL_ID        BIGINT
);
ALTER TABLE PUBLIC.MARK
    ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY (ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MARK;
CREATE CACHED TABLE PUBLIC.POST
(
    ID          BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9F8EBA1E_9F52_4CEC_8BE5_6ACBB342DCEA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9F8EBA1E_9F52_4CEC_8BE5_6ACBB342DCEA,
    ADDED_DATE  TIMESTAMP,
    POST_BODY   VARCHAR(255),
    POST_TITLE  VARCHAR(255),
    POST_AUTHOR BIGINT
);
ALTER TABLE PUBLIC.POST
    ADD CONSTRAINT PUBLIC.CONSTRAINT_25 PRIMARY KEY (ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.POST;
CREATE CACHED TABLE PUBLIC.ROLE
(
    ID        BIGINT NOT NULL,
    ROLE_NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.ROLE
    ADD CONSTRAINT PUBLIC.CONSTRAINT_26 PRIMARY KEY (ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE CACHED TABLE PUBLIC.SCHOOL_CLASS
(
    ID            BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_027150CA_4473_413D_834C_48D27A10D6E2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_027150CA_4473_413D_834C_48D27A10D6E2,
    CLASS_NAME    VARCHAR(255),
    CLASS_PROFILE VARCHAR(255),
    EDUCATOR_ID   BIGINT
);
ALTER TABLE PUBLIC.SCHOOL_CLASS
    ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY (ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SCHOOL_CLASS;
CREATE CACHED TABLE PUBLIC.SUBJECT
(
    ID           BIGINT NOT NULL,
    SUBJECT_NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.SUBJECT
    ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY (ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUBJECT;
CREATE CACHED TABLE PUBLIC.USER
(
    ID              BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DEE8149F_D4B4_413D_9032_511DCDF6D45F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DEE8149F_D4B4_413D_9032_511DCDF6D45F,
    ADDED_DATE      TIMESTAMP,
    EMAIL           VARCHAR(255),
    LAST_NAME       VARCHAR(255),
    NAME            VARCHAR(255),
    PASSWORD        VARCHAR(255),
    BIRTH_DATE      DATE,
    SCHOOL_CLASS_ID BIGINT
);
ALTER TABLE PUBLIC.USER
    ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY (ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER;
CREATE CACHED TABLE PUBLIC.USER_MARK
(
    USER_ID     BIGINT NOT NULL,
    MARK_SET_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.USER_MARK
    ADD CONSTRAINT PUBLIC.CONSTRAINT_BC PRIMARY KEY (USER_ID, MARK_SET_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_MARK;
CREATE CACHED TABLE PUBLIC.USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.USER_ROLE
    ADD CONSTRAINT PUBLIC.CONSTRAINT_BC1 PRIMARY KEY (USER_ID, ROLE_ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;
CREATE CACHED TABLE PUBLIC.USER_SUBJECT
(
    USER_ID        BIGINT NOT NULL,
    SUBJECT_SET_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.USER_SUBJECT
    ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY (USER_ID, SUBJECT_SET_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_SUBJECT;
ALTER TABLE PUBLIC.POST
    ADD CONSTRAINT PUBLIC.FK3VBN48VT3LMR0BBDA49YGK8L9 FOREIGN KEY (POST_AUTHOR) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_SUBJECT
    ADD CONSTRAINT PUBLIC.FKL0O2KSTFY6Q3U6667N8I55N63 FOREIGN KEY (SUBJECT_SET_ID) REFERENCES PUBLIC.SUBJECT (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_SUBJECT
    ADD CONSTRAINT PUBLIC.FKGEG9UD2LPOD26ABH4X3WXC17K FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_MARK
    ADD CONSTRAINT PUBLIC.FK9M83K122HLFBXVOUQP0OU87BA FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.MARK
    ADD CONSTRAINT PUBLIC.FKT6KC1AOLBA30LD4M8FQMCRT1Q FOREIGN KEY (SUBJECT_ID) REFERENCES PUBLIC.SUBJECT (ID) NOCHECK;
ALTER TABLE PUBLIC.MARK
    ADD CONSTRAINT PUBLIC.FKHRG5STNW0LMWCHXV7LQ6PN9VA FOREIGN KEY (TEACHER_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.MARK
    ADD CONSTRAINT PUBLIC.FK6WF9X6Q8VCR1VCTYTWCYIW3U5 FOREIGN KEY (PUPIL_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.USER
    ADD CONSTRAINT PUBLIC.FKKNWS0U0J3AHTYPIEB9QQQG3B1 FOREIGN KEY (SCHOOL_CLASS_ID) REFERENCES PUBLIC.SCHOOL_CLASS (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE
    ADD CONSTRAINT PUBLIC.FK859N2JVI8IVHUI0RL0ESWS6O FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_MARK
    ADD CONSTRAINT PUBLIC.FK8V206MPBLRO7LVSVBS5RJGTD FOREIGN KEY (MARK_SET_ID) REFERENCES PUBLIC.MARK (ID) NOCHECK;
ALTER TABLE PUBLIC.SCHOOL_CLASS
    ADD CONSTRAINT PUBLIC.FK3CLAJVIXO43VBFX4CU3MSF0SG FOREIGN KEY (EDUCATOR_ID) REFERENCES PUBLIC.USER (ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE
    ADD CONSTRAINT PUBLIC.FKA68196081FVOVJHKEK5M97N3Y FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.ROLE (ID) NOCHECK;